CREATE TABLE Users (
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL,
  phone VARCHAR(15),
  address VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Services (
  id SERIAL PRIMARY KEY,
  service_name VARCHAR(30) NOT NULL,
  unit VARCHAR(20) NOT NULL,
  price DOUBLE PRECISION,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transactions (
  id UUID PRIMARY KEY NOT NULL,
  received_by VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP
);

CREATE TABLE Trx_Detail (
  id UUID PRIMARY KEY NOT NULL,
  transaction_id UUID NOT NULL,
  user_id UUID NOT NULL,
  service_id INT NOT NULL,
  quantity INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id),
  FOREIGN KEY (service_id) REFERENCES Services(id)
);
